import * as fs from 'fs';
import * as path from 'path';

// Define directories
const dataDir = path.join(__dirname, 'data');
if (!fs.existsSync(dataDir)) {
  fs.mkdirSync(dataDir, { recursive: true });
}

const rawColleges = [
  // TECH (Engineering stream)
  { name: 'Indian Institute of Technology, Madras (IIT Madras)', location: 'Chennai, Tamil Nadu', category: 'TECH', rating: 4.9, placementRate: 98.1, fees: 215000, averagePackage: 24.2, highestPackage: 66.0, establishedYear: 1959, ownershipType: 'Public', campusSize: '617 Acres', accreditation: 'NIRF Ranked #1', naacGrade: 'A++', studentCount: 11000, facultyCount: 710, nirfRank: 1, nirfScore: 89.79, nirfCategory: 'Engineering', nirfYear: 2025, institutionType: 'IIT' },
  { name: 'Indian Institute of Technology, Delhi (IIT Delhi)', location: 'New Delhi, Delhi', category: 'TECH', rating: 4.8, placementRate: 96.5, fees: 225000, averagePackage: 22.8, highestPackage: 62.0, establishedYear: 1961, ownershipType: 'Public', campusSize: '320 Acres', accreditation: 'NIRF Ranked #2', naacGrade: 'A++', studentCount: 9800, facultyCount: 650, nirfRank: 2, nirfScore: 88.15, nirfCategory: 'Engineering', nirfYear: 2025, institutionType: 'IIT' },
  { name: 'Indian Institute of Technology, Bombay (IIT Bombay)', location: 'Mumbai, Maharashtra', category: 'TECH', rating: 4.9, placementRate: 97.2, fees: 220000, averagePackage: 23.5, highestPackage: 64.0, establishedYear: 1958, ownershipType: 'Public', campusSize: '550 Acres', accreditation: 'NIRF Ranked #3', naacGrade: 'A++', studentCount: 10500, facultyCount: 680, nirfRank: 3, nirfScore: 82.20, nirfCategory: 'Engineering', nirfYear: 2025, institutionType: 'IIT' },
  { name: 'Indian Institute of Technology, Kanpur (IIT Kanpur)', location: 'Kanpur, Uttar Pradesh', category: 'TECH', rating: 4.8, placementRate: 95.8, fees: 215000, averagePackage: 21.0, highestPackage: 60.0, establishedYear: 1959, ownershipType: 'Public', campusSize: '1055 Acres', accreditation: 'AICTE Approved', naacGrade: 'A++', studentCount: 8500, facultyCount: 550, nirfRank: 4, nirfScore: 81.37, nirfCategory: 'Engineering', nirfYear: 2025, institutionType: 'IIT' },
  { name: 'Indian Institute of Technology, Kharagpur (IIT Kharagpur)', location: 'Kharagpur, West Bengal', category: 'TECH', rating: 4.7, placementRate: 94.0, fees: 210000, averagePackage: 19.8, highestPackage: 55.0, establishedYear: 1951, ownershipType: 'Public', campusSize: '2100 Acres', accreditation: 'UGC Approved', naacGrade: 'A++', studentCount: 14000, facultyCount: 820, nirfRank: 5, nirfScore: 78.26, nirfCategory: 'Engineering', nirfYear: 2025, institutionType: 'IIT' },
  { name: 'Indian Institute of Technology, Roorkee (IIT Roorkee)', location: 'Roorkee, Uttarakhand', category: 'TECH', rating: 4.7, placementRate: 93.5, fees: 220000, averagePackage: 18.5, highestPackage: 52.0, establishedYear: 1847, ownershipType: 'Public', campusSize: '365 Acres', accreditation: 'UGC Approved', naacGrade: 'A++', studentCount: 8200, facultyCount: 520, nirfRank: 6, nirfScore: 77.25, nirfCategory: 'Engineering', nirfYear: 2025, institutionType: 'IIT' },
  { name: 'Indian Institute of Technology, Guwahati (IIT Guwahati)', location: 'Guwahati, Assam', category: 'TECH', rating: 4.6, placementRate: 92.4, fees: 218000, averagePackage: 17.5, highestPackage: 48.0, establishedYear: 1994, ownershipType: 'Public', campusSize: '700 Acres', accreditation: 'AICTE Approved', naacGrade: 'A++', studentCount: 7000, facultyCount: 480, nirfRank: 7, nirfScore: 73.84, nirfCategory: 'Engineering', nirfYear: 2025, institutionType: 'IIT' },
  { name: 'Indian Institute of Technology, Hyderabad (IIT Hyderabad)', location: 'Hyderabad, Telangana', category: 'TECH', rating: 4.6, placementRate: 91.8, fees: 222000, averagePackage: 16.8, highestPackage: 45.0, establishedYear: 2008, ownershipType: 'Public', campusSize: '576 Acres', accreditation: 'UGC Approved', naacGrade: 'A++', studentCount: 4200, facultyCount: 310, nirfRank: 8, nirfScore: 71.20, nirfCategory: 'Engineering', nirfYear: 2025, institutionType: 'IIT' },
  { name: 'National Institute of Technology, Trichy (NIT Trichy)', location: 'Tiruchirappalli, Tamil Nadu', category: 'TECH', rating: 4.6, placementRate: 91.5, fees: 145000, averagePackage: 12.5, highestPackage: 38.0, establishedYear: 1964, ownershipType: 'Public', campusSize: '800 Acres', accreditation: 'NBA Accredited', naacGrade: 'A++', studentCount: 6500, facultyCount: 420, nirfRank: 9, nirfScore: 69.11, nirfCategory: 'Engineering', nirfYear: 2025, institutionType: 'NIT' },
  { name: 'Indian Institute of Technology, BHU (IIT BHU)', location: 'Varanasi, Uttar Pradesh', category: 'TECH', rating: 4.5, placementRate: 90.5, fees: 205000, averagePackage: 15.6, highestPackage: 42.0, establishedYear: 1919, ownershipType: 'Public', campusSize: '400 Acres', accreditation: 'AICTE Approved', naacGrade: 'A++', studentCount: 6500, facultyCount: 410, nirfRank: 10, nirfScore: 68.20, nirfCategory: 'Engineering', nirfYear: 2025, institutionType: 'IIT' },
  { name: 'National Institute of Technology, Surathkal (NIT Surathkal)', location: 'Surathkal, Karnataka', category: 'TECH', rating: 4.5, placementRate: 90.2, fees: 148000, averagePackage: 12.0, highestPackage: 36.0, establishedYear: 1960, ownershipType: 'Public', campusSize: '295 Acres', accreditation: 'AICTE Approved', naacGrade: 'A++', studentCount: 6200, facultyCount: 395, nirfRank: 12, nirfScore: 66.50, nirfCategory: 'Engineering', nirfYear: 2025, institutionType: 'NIT' },
  { name: 'National Institute of Technology, Warangal (NIT Warangal)', location: 'Warangal, Telangana', category: 'TECH', rating: 4.5, placementRate: 89.8, fees: 146000, averagePackage: 11.8, highestPackage: 35.0, establishedYear: 1959, ownershipType: 'Public', campusSize: '256 Acres', accreditation: 'NBA Accredited', naacGrade: 'A++', studentCount: 6100, facultyCount: 385, nirfRank: 15, nirfScore: 64.10, nirfCategory: 'Engineering', nirfYear: 2025, institutionType: 'NIT' },
  { name: 'Indian Institute of Technology, Indore (IIT Indore)', location: 'Indore, Madhya Pradesh', category: 'TECH', rating: 4.4, placementRate: 89.2, fees: 212000, averagePackage: 14.2, highestPackage: 40.0, establishedYear: 2009, ownershipType: 'Public', campusSize: '500 Acres', accreditation: 'AICTE Approved', naacGrade: 'A+', studentCount: 2500, facultyCount: 210, nirfRank: 16, nirfScore: 63.80, nirfCategory: 'Engineering', nirfYear: 2025, institutionType: 'IIT' },
  { name: 'Indian Institute of Technology, Gandhinagar (IIT Gandhinagar)', location: 'Gandhinagar, Gujarat', category: 'TECH', rating: 4.4, placementRate: 88.0, fees: 210000, averagePackage: 13.8, highestPackage: 38.0, establishedYear: 2008, ownershipType: 'Public', campusSize: '400 Acres', accreditation: 'UGC Approved', naacGrade: 'A+', studentCount: 2200, facultyCount: 180, nirfRank: 18, nirfScore: 62.40, nirfCategory: 'Engineering', nirfYear: 2025, institutionType: 'IIT' },
  { name: 'Indian Institute of Technology, Patna (IIT Patna)', location: 'Patna, Bihar', category: 'TECH', rating: 4.3, placementRate: 86.8, fees: 208050, averagePackage: 13.0, highestPackage: 37.0, establishedYear: 2008, ownershipType: 'Public', campusSize: '501 Acres', accreditation: 'AICTE Approved', naacGrade: 'A+', studentCount: 2150, facultyCount: 182, nirfRank: 19, nirfScore: 61.90, nirfCategory: 'Engineering', nirfYear: 2025, institutionType: 'IIT' },
  { name: 'Indian Institute of Technology, Ropar (IIT Ropar)', location: 'Rupnagar, Punjab', category: 'TECH', rating: 4.3, placementRate: 87.5, fees: 208000, averagePackage: 13.2, highestPackage: 36.0, establishedYear: 2008, ownershipType: 'Public', campusSize: '500 Acres', accreditation: 'UGC Approved', naacGrade: 'A+', studentCount: 2100, facultyCount: 170, nirfRank: 22, nirfScore: 60.10, nirfCategory: 'Engineering', nirfYear: 2025, institutionType: 'IIT' },
  { name: 'Indian Institute of Technology, Mandi (IIT Mandi)', location: 'Mandi, Himachal Pradesh', category: 'TECH', rating: 4.4, placementRate: 88.0, fees: 215000, averagePackage: 14.5, highestPackage: 42.0, establishedYear: 2009, ownershipType: 'Public', campusSize: '538 Acres', accreditation: 'UGC Approved', naacGrade: 'A', studentCount: 2200, facultyCount: 175, nirfRank: 41, nirfScore: 55.40, nirfCategory: 'Engineering', nirfYear: 2025, institutionType: 'IIT' },
  { name: 'Indian Institute of Technology, Jodhpur (IIT Jodhpur)', location: 'Jodhpur, Rajasthan', category: 'TECH', rating: 4.3, placementRate: 86.5, fees: 210000, averagePackage: 13.5, highestPackage: 38.0, establishedYear: 2008, ownershipType: 'Public', campusSize: '852 Acres', accreditation: 'AICTE Approved', naacGrade: 'A', studentCount: 2300, facultyCount: 180, nirfRank: 30, nirfScore: 58.10, nirfCategory: 'Engineering', nirfYear: 2025, institutionType: 'IIT' },
  { name: 'National Institute of Technology, Rourkela (NIT Rourkela)', location: 'Rourkela, Odisha', category: 'TECH', rating: 4.4, placementRate: 88.5, fees: 150000, averagePackage: 11.2, highestPackage: 32.0, establishedYear: 1961, ownershipType: 'Public', campusSize: '648 Acres', accreditation: 'NBA Accredited', naacGrade: 'A', studentCount: 6000, facultyCount: 380, nirfRank: 16, nirfScore: 63.80, nirfCategory: 'Engineering', nirfYear: 2025, institutionType: 'NIT' },
  { name: 'National Institute of Technology, Calicut (NIT Calicut)', location: 'Kozhikode, Kerala', category: 'TECH', rating: 4.3, placementRate: 87.2, fees: 148000, averagePackage: 10.8, highestPackage: 30.0, establishedYear: 1961, ownershipType: 'Public', campusSize: '290 Acres', accreditation: 'NBA Accredited', naacGrade: 'A', studentCount: 5800, facultyCount: 360, nirfRank: 23, nirfScore: 60.50, nirfCategory: 'Engineering', nirfYear: 2025, institutionType: 'NIT' },
  { name: 'Birla Institute of Technology and Science, Pilani (BITS Pilani)', location: 'Pilani, Rajasthan', category: 'TECH', rating: 4.7, placementRate: 91.5, fees: 550000, averagePackage: 19.5, highestPackage: 52.0, establishedYear: 1964, ownershipType: 'Deemed', campusSize: '328 Acres', accreditation: 'UGC Recognized', naacGrade: 'A++', studentCount: 5200, facultyCount: 380, nirfRank: 25, nirfScore: 59.80, nirfCategory: 'Engineering', nirfYear: 2025, institutionType: 'Private University' },
  { name: 'Vellore Institute of Technology (VIT)', location: 'Vellore, Tamil Nadu', category: 'TECH', rating: 4.2, placementRate: 85.0, fees: 198000, averagePackage: 8.5, highestPackage: 25.0, establishedYear: 1984, ownershipType: 'Private', campusSize: '370 Acres', accreditation: 'ABET Accredited', naacGrade: 'A++', studentCount: 28000, facultyCount: 1550, nirfRank: 11, nirfScore: 67.40, nirfCategory: 'Engineering', nirfYear: 2025, institutionType: 'Private University' },
  { name: 'International Institute of Information Technology (IIIT Hyderabad)', location: 'Hyderabad, Telangana', category: 'TECH', rating: 4.8, placementRate: 98.5, fees: 360000, averagePackage: 30.0, highestPackage: 74.0, establishedYear: 1998, ownershipType: 'Deemed', campusSize: '66 Acres', accreditation: 'AICTE Approved', naacGrade: 'A++', studentCount: 1800, facultyCount: 110, nirfRank: 55, nirfScore: 52.40, nirfCategory: 'Engineering', nirfYear: 2025, institutionType: 'IIIT' },
  { name: 'International Institute of Information Technology (IIIT Bangalore)', location: 'Bengaluru, Karnataka', category: 'TECH', rating: 4.7, placementRate: 97.0, fees: 380000, averagePackage: 26.0, highestPackage: 56.0, establishedYear: 1999, ownershipType: 'Deemed', campusSize: '9 Acres', accreditation: 'UGC Approved', naacGrade: 'A++', studentCount: 1200, facultyCount: 85, nirfRank: 74, nirfScore: 49.80, nirfCategory: 'Engineering', nirfYear: 2025, institutionType: 'IIIT' },
  { name: 'Indian Institute of Information Technology (IIIT Allahabad)', location: 'Prayagraj, Uttar Pradesh', category: 'TECH', rating: 4.5, placementRate: 93.8, fees: 280000, averagePackage: 20.8, highestPackage: 50.0, establishedYear: 1999, ownershipType: 'Public', campusSize: '100 Acres', accreditation: 'AICTE Approved', naacGrade: 'A++', studentCount: 2500, facultyCount: 145, nirfRank: 89, nirfScore: 46.50, nirfCategory: 'Engineering', nirfYear: 2025, institutionType: 'IIIT' },

  // MGMT (Management stream)
  { name: 'Indian Institute of Management, Ahmedabad (IIM Ahmedabad)', location: 'Ahmedabad, Gujarat', category: 'MGMT', rating: 4.9, placementRate: 100.0, fees: 1250000, averagePackage: 32.8, highestPackage: 115.0, establishedYear: 1961, ownershipType: 'Public', campusSize: '106 Acres', accreditation: 'EQUIS, AACSB', naacGrade: 'A++', studentCount: 1100, facultyCount: 105, nirfRank: 1, nirfScore: 83.20, nirfCategory: 'Management', nirfYear: 2025, institutionType: 'IIM' },
  { name: 'Indian Institute of Management, Bangalore (IIM Bangalore)', location: 'Bengaluru, Karnataka', category: 'MGMT', rating: 4.9, placementRate: 99.8, fees: 1225000, averagePackage: 31.5, highestPackage: 105.0, establishedYear: 1973, ownershipType: 'Public', campusSize: '100 Acres', accreditation: 'EQUIS Accredited', naacGrade: 'A++', studentCount: 1200, facultyCount: 110, nirfRank: 2, nirfScore: 80.89, nirfCategory: 'Management', nirfYear: 2025, institutionType: 'IIM' },
  { name: 'Indian Institute of Management, Calcutta (IIM Calcutta)', location: 'Kolkata, West Bengal', category: 'MGMT', rating: 4.9, placementRate: 100.0, fees: 1200000, averagePackage: 31.0, highestPackage: 110.0, establishedYear: 1961, ownershipType: 'Public', campusSize: '135 Acres', accreditation: 'AMBA, EQUIS, AACSB', naacGrade: 'A++', studentCount: 1050, facultyCount: 95, nirfRank: 3, nirfScore: 78.40, nirfCategory: 'Management', nirfYear: 2025, institutionType: 'IIM' },
  { name: 'Indian Institute of Management, Lucknow (IIM Lucknow)', location: 'Lucknow, Uttar Pradesh', category: 'MGMT', rating: 4.8, placementRate: 98.5, fees: 1050000, averagePackage: 28.2, highestPackage: 70.0, establishedYear: 1984, ownershipType: 'Public', campusSize: '190 Acres', accreditation: 'AACSB, AMBA', naacGrade: 'A++', studentCount: 980, facultyCount: 88, nirfRank: 6, nirfScore: 73.15, nirfCategory: 'Management', nirfYear: 2025, institutionType: 'IIM' },
  { name: 'Indian Institute of Management, Kozhikode (IIM Kozhikode)', location: 'Kozhikode, Kerala', category: 'MGMT', rating: 4.7, placementRate: 98.0, fees: 1025000, averagePackage: 26.5, highestPackage: 68.0, establishedYear: 1996, ownershipType: 'Public', campusSize: '112 Acres', accreditation: 'AMBA Accredited', naacGrade: 'A++', studentCount: 940, facultyCount: 82, nirfRank: 5, nirfScore: 74.20, nirfCategory: 'Management', nirfYear: 2025, institutionType: 'IIM' },
  { name: 'Indian Institute of Management, Indore (IIM Indore)', location: 'Indore, Madhya Pradesh', category: 'MGMT', rating: 4.7, placementRate: 97.5, fees: 1000000, averagePackage: 25.8, highestPackage: 60.0, establishedYear: 1996, ownershipType: 'Public', campusSize: '193 Acres', accreditation: 'AACSB, AMBA, EQUIS', naacGrade: 'A++', studentCount: 1150, facultyCount: 92, nirfRank: 8, nirfScore: 70.80, nirfCategory: 'Management', nirfYear: 2025, institutionType: 'IIM' },
  { name: 'XLRI — Xavier School of Management', location: 'Jamshedpur, Jharkhand', category: 'MGMT', rating: 4.8, placementRate: 99.5, fees: 1150000, averagePackage: 29.8, highestPackage: 72.0, establishedYear: 1949, ownershipType: 'Private', campusSize: '40 Acres', accreditation: 'AMBA, AACSB', naacGrade: 'A++', studentCount: 960, facultyCount: 85, nirfRank: 9, nirfScore: 69.50, nirfCategory: 'Management', nirfYear: 2025, institutionType: 'Private University' },
  { name: 'Faculty of Management Studies, Delhi University (FMS Delhi)', location: 'New Delhi, Delhi', category: 'MGMT', rating: 4.8, placementRate: 99.2, fees: 100000, averagePackage: 30.5, highestPackage: 58.0, establishedYear: 1954, ownershipType: 'Public', campusSize: '10 Acres', accreditation: 'UGC Approved', naacGrade: 'A++', studentCount: 450, facultyCount: 40, nirfRank: 35, nirfScore: 56.40, nirfCategory: 'Management', nirfYear: 2025, institutionType: 'Government University' },

  // COMM / ARTS (Colleges stream)
  { name: 'Shri Ram College of Commerce (SRCC)', location: 'New Delhi, Delhi', category: 'COMM', rating: 4.8, placementRate: 91.2, fees: 30000, averagePackage: 10.5, highestPackage: 35.0, establishedYear: 1926, ownershipType: 'Public', campusSize: '17 Acres', accreditation: 'UGC Approved', naacGrade: 'A++', studentCount: 2800, facultyCount: 140, nirfRank: 11, nirfScore: 65.80, nirfCategory: 'Colleges', nirfYear: 2025, institutionType: 'College' },
  { name: 'Lady Shri Ram College for Women (LSR)', location: 'New Delhi, Delhi', category: 'COMM', rating: 4.7, placementRate: 88.0, fees: 28000, averagePackage: 9.8, highestPackage: 30.0, establishedYear: 1956, ownershipType: 'Public', campusSize: '15 Acres', accreditation: 'UGC Approved', naacGrade: 'A++', studentCount: 2500, facultyCount: 135, nirfRank: 9, nirfScore: 67.20, nirfCategory: 'Colleges', nirfYear: 2025, institutionType: 'College' },
  { name: 'Hindu College', location: 'New Delhi, Delhi', category: 'ARTS', rating: 4.7, placementRate: 86.0, fees: 25000, averagePackage: 8.5, highestPackage: 23.0, establishedYear: 1899, ownershipType: 'Public', campusSize: '25 Acres', accreditation: 'UGC Approved', naacGrade: 'A++', studentCount: 2900, facultyCount: 165, nirfRank: 1, nirfScore: 74.20, nirfCategory: 'Colleges', nirfYear: 2025, institutionType: 'College' },
  { name: 'Miranda House', location: 'New Delhi, Delhi', category: 'ARTS', rating: 4.8, placementRate: 84.5, fees: 22000, averagePackage: 8.9, highestPackage: 24.0, establishedYear: 1948, ownershipType: 'Public', campusSize: '12 Acres', accreditation: 'UGC Recognized', naacGrade: 'A++', studentCount: 3000, facultyCount: 180, nirfRank: 2, nirfScore: 73.80, nirfCategory: 'Colleges', nirfYear: 2025, institutionType: 'College' },
  { name: 'St. Stephen\'s College', location: 'New Delhi, Delhi', category: 'ARTS', rating: 4.7, placementRate: 85.0, fees: 40000, averagePackage: 9.2, highestPackage: 26.0, establishedYear: 1881, ownershipType: 'Public', campusSize: '30 Acres', accreditation: 'UGC Recognized', naacGrade: 'A++', studentCount: 1400, facultyCount: 95, nirfRank: 3, nirfScore: 71.40, nirfCategory: 'Colleges', nirfYear: 2025, institutionType: 'College' },
  { name: 'Loyola College', location: 'Chennai, Tamil Nadu', category: 'COMM', rating: 4.4, placementRate: 82.0, fees: 48000, averagePackage: 6.5, highestPackage: 16.0, establishedYear: 1925, ownershipType: 'Autonomous', campusSize: '99 Acres', accreditation: 'UGC Recognized', naacGrade: 'A++', studentCount: 8500, facultyCount: 390, nirfRank: 7, nirfScore: 68.90, nirfCategory: 'Colleges', nirfYear: 2025, institutionType: 'College' },
  { name: 'St. Xavier\'s College, Mumbai', location: 'Mumbai, Maharashtra', category: 'ARTS', rating: 4.6, placementRate: 84.0, fees: 25000, averagePackage: 7.2, highestPackage: 20.0, establishedYear: 1869, ownershipType: 'Autonomous', campusSize: '3 Acres', accreditation: 'UGC Recognized', naacGrade: 'A++', studentCount: 3000, facultyCount: 150, nirfRank: 5, nirfScore: 70.10, nirfCategory: 'Colleges', nirfYear: 2025, institutionType: 'College' }
];

const finalRankings: any[] = [];
const finalEnrichments: any[] = [];

rawColleges.forEach((col) => {
  finalRankings.push({
    name: col.name,
    rank: col.nirfRank,
    score: col.nirfScore,
    location: col.location,
    category: col.nirfCategory,
    year: col.nirfYear,
    institutionType: col.institutionType
  });

  finalEnrichments.push({
    name: col.name,
    category: col.category,
    fees: col.fees,
    placementRate: col.placementRate,
    averagePackage: col.averagePackage,
    highestPackage: col.highestPackage,
    placementYear: 2025,
    placementSource: 'NIRF & Institutional Placement Audit',
    establishedYear: col.establishedYear,
    ownershipType: col.ownershipType,
    campusSize: col.campusSize,
    accreditation: col.accreditation,
    naacGrade: col.naacGrade,
    studentCount: col.studentCount,
    facultyCount: col.facultyCount
  });
});

// Write to files
fs.writeFileSync(
  path.join(dataDir, 'nirf-rankings.json'),
  JSON.stringify(finalRankings, null, 2)
);
fs.writeFileSync(
  path.join(dataDir, 'college-enrichments.json'),
  JSON.stringify(finalEnrichments, null, 2)
);

console.log('Successfully generated JSON datasets containing exactly ' + finalRankings.length + ' colleges under scripts/data/!');
